# config/application.yml
defaults: &defaults
  pdfpages:
    pagelocation: "#{Rails.root}/pdf_pages"
  tdl_feedback_address: "brian.goodmon@tufts.edu"
  tdl_feedback_subject: "TDL Content Feedback"

development:
  <<: *defaults
  neat_setting: 800

tdldev:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  tdl_feedback_address: "deborah.kaplan@tufts.edu"
