# config/application.yml
defaults: &defaults
  pdf_pages:
    page_location: "#{Rails.root}/pdf_pages"
  tdl_feedback_address: "brian.goodmon@tufts.edu"
  tdl_feedback_subject: "TDL Content Feedback"
  local_object_store: "#{Rails.root}/local_object_store"
  trim_bucket_url: "http://bucket01.lib.tufts.edu"

development:
  <<: *defaults
  neat_setting: 800

tdldev:
  <<: *defaults
  local_object_store: "/tdr"
test:
  <<: *defaults
  local_object_store: "/tdr"
production:
  <<: *defaults
  tdl_feedback_address: "deborah.kaplan@tufts.edu"
  local_object_store: "/tdr"